#! /bin/bash

echo "Do you want to Backup"
read ans
if [ $ans = 'y' ]
then
	echo "Enter path for which you want Backup"
	read p
	echo "Enter path where you want to store"
	read p1
	cp -r $p $p1
	zip -r myfile.zip $p1
	tar -cvf $p1

	echo "Hello This is my Test mail2" | sendemail -a myfile.zip -f "style9720887089@gmail.com"      -u "Backup"      -t "style9720887089@gmail.com"      -cc "bhardwaj_himanshu@hotmail.com"   -s "smtp.gmail.com:587"      -o tls=yes      -xu "style9720887089@gmail.com"      -xp "9759497994Hb"


fi

