#! /bin/bash

df | cut -c54-75 | sed -e 's/se/0/g'>m

for u in $( cut -c1-2 m )
do
	if [ $u -gt 20 ]
	then 
		tput setaf 3;
		echo "Alert the memory utalization is $u% "
	tput setaf 1;
		echo "Please check alert at  `df | awk '{print ( $5 , $6)}'` "
	
		tput sgr0;
fi
done
